// Inventory Request and Audit Types

import { InventoryItem } from './inventoryData';

// Request Types
export type RequestType =
  | 'item-addition'      // Request to add new item
  | 'item-edit'          // Request to edit existing item
  | 'storage-move'       // Request to move item to different storage
  | 'stock-adjustment'   // Request to adjust stock levels
  | 'item-deletion';     // Request to delete item

export type RequestStatus =
  | 'pending'     // Waiting for admin review
  | 'approved'    // Admin approved
  | 'rejected';   // Admin rejected

export interface InventoryRequest {
  id: string;
  type: RequestType;
  status: RequestStatus;

  // Submitter info
  submittedBy: string;           // Staff member name/ID
  submittedAt: string;           // ISO timestamp

  // Request details (varies by type)
  itemId?: string;               // For edit/delete/move requests
  itemData?: Partial<InventoryItem>; // For addition/edit requests
  storageChange?: {
    fromLocationId: string;
    fromContainerId: string;
    toLocationId: string;
    toContainerId: string;
  };
  stockAdjustment?: {
    currentStock: number;
    requestedStock: number;
    reason: string;
  };

  // Description and justification
  description: string;
  reason?: string;

  // Admin response
  reviewedBy?: string;           // Admin who reviewed
  reviewedAt?: string;           // ISO timestamp
  reviewResponse?: string;       // Admin's response/notes
}

// Audit Types
export type AuditStatus =
  | 'pending'     // Assigned but not started
  | 'in-progress' // Staff is working on it
  | 'completed';  // Audit completed

export type AuditType =
  | 'location'    // Audit entire location
  | 'container'   // Audit specific container
  | 'item'        // Audit specific item across all locations
  | 'full';       // Full inventory audit

export interface AuditTask {
  id: string;
  type: AuditType;
  status: AuditStatus;

  // Assignment
  createdBy: string;             // Admin who created
  createdAt: string;             // ISO timestamp
  assignedTo?: string;           // Specific staff member (optional)
  isBroadcast: boolean;          // True if open to any staff

  // Audit scope
  locationId?: string;
  containerId?: string;
  itemId?: string;

  // Instructions
  title: string;
  instructions?: string;
  priority: 'low' | 'medium' | 'high' | 'urgent';
  dueDate?: string;              // ISO date

  // Completion
  completedBy?: string;          // Staff who completed
  completedAt?: string;          // ISO timestamp
  results?: AuditResult[];
  notes?: string;
}

export interface AuditResult {
  itemId: string;
  itemName: string;
  expectedCount: number;
  actualCount: number;
  discrepancy: number;           // actualCount - expectedCount
  condition?: 'good' | 'damaged' | 'expired' | 'missing';
  notes?: string;
}

// Reorder Types
export type ReorderPriority = 'urgent' | 'high' | 'medium' | 'low';

export interface ReorderAlert {
  id: string;
  itemId: string;
  item: InventoryItem;

  // Stock info
  currentStock: number;
  reorderPoint: number;
  minimumStock: number;
  recommendedOrderQuantity: number;

  // Urgency calculation
  priority: ReorderPriority;
  daysUntilEmpty?: number;       // Predicted based on usage
  isAutoGenerated: boolean;      // True if system-generated

  // Metadata
  createdAt: string;             // ISO timestamp
  lastUpdated: string;           // ISO timestamp
}

export interface PurchaseOrder {
  id: string;
  status: 'draft' | 'pending' | 'approved' | 'ordered' | 'received' | 'cancelled';

  // Items
  items: {
    itemId: string;
    itemName: string;
    quantity: number;
    unitCost?: number;
    totalCost?: number;
  }[];

  // Totals
  totalItems: number;
  totalCost?: number;

  // Supplier
  supplier: string;
  supplierContact?: string;

  // Metadata
  createdBy: string;
  createdAt: string;
  approvedBy?: string;
  approvedAt?: string;
  orderedAt?: string;
  expectedDelivery?: string;
  receivedAt?: string;

  notes?: string;
}

// Usage Tracking (for smart reordering)
export interface ItemUsage {
  itemId: string;
  date: string;                  // ISO date
  quantityUsed: number;
  usedBy?: string;               // Staff member
  procedureId?: string;          // If linked to a procedure
  notes?: string;
}

export interface UsageStats {
  itemId: string;

  // Consumption rates
  dailyAverage: number;
  weeklyAverage: number;
  monthlyAverage: number;

  // Trends
  trend: 'increasing' | 'stable' | 'decreasing';

  // Predictions
  predictedEmptyDate?: string;   // When stock will hit zero
  predictedReorderDate?: string; // When stock will hit reorder point

  // Historical data
  lastUsed?: string;             // ISO timestamp
  totalUsageCount: number;
  averageUsagePerProcedure?: number;
}
