// Script to generate all 810 procedures for Royal London Hospital
// This will output the procedures array to paste into the API route

const procedures = [
  // ============================================
  // EMERGENCY (30 procedures - no subspecialty)
  // ============================================
  { name: 'Laparotomy - Exploratory', specialtyName: 'Emergency', opcs4: ['T421'], commonVariations: ['Ex-Lap', 'Emergency Laparotomy'] },
  { name: 'Appendicectomy - Emergency', specialtyName: 'Emergency', opcs4: ['H011', 'H012'], commonVariations: ['Emergency Appendicectomy', 'Appy'] },
  { name: 'Laparotomy for Perforated Viscus', specialtyName: 'Emergency', opcs4: ['T421', 'G512'], commonVariations: ['Perforation Repair'] },
  { name: 'Emergency Bowel Resection', specialtyName: 'Emergency', opcs4: ['G761', 'H061'], commonVariations: ['Emergency Colectomy'] },
  { name: 'Damage Control Laparotomy', specialtyName: 'Emergency', opcs4: ['T421'], commonVariations: ['DCL'] },
  { name: 'Trauma Laparotomy', specialtyName: 'Emergency', opcs4: ['T421'], commonVariations: ['Emergency Trauma Surgery'] },
  { name: 'Emergency Hernia Repair', specialtyName: 'Emergency', opcs4: ['T201'], commonVariations: ['Strangulated Hernia Repair'] },
  { name: 'Incarcerated Hernia Repair', specialtyName: 'Emergency', opcs4: ['T201'], commonVariations: ['Obstructed Hernia Repair'] },
  { name: 'Emergency Cholecystectomy', specialtyName: 'Emergency', opcs4: ['J181'], commonVariations: ['Urgent Gallbladder Removal'] },
  { name: 'Abscess Drainage - Intra-abdominal', specialtyName: 'Emergency', opcs4: ['T481'], commonVariations: ['Collection Drainage'] },
  { name: 'Necrotising Fasciitis Debridement', specialtyName: 'Emergency', opcs4: ['S571'], commonVariations: ['NF Debridement'] },
  { name: 'Small Bowel Obstruction Release', specialtyName: 'Emergency', opcs4: ['T781'], commonVariations: ['Adhesiolysis'] },
  { name: 'Peptic Ulcer Perforation Repair', specialtyName: 'Emergency', opcs4: ['G512'], commonVariations: ['Omental Patch Repair'] },
  { name: 'Bleeding Peptic Ulcer Repair', specialtyName: 'Emergency', opcs4: ['G512'], commonVariations: ['Under-running of Ulcer'] },
  { name: 'Emergency Splenectomy', specialtyName: 'Emergency', opcs4: ['T701'], commonVariations: ['Trauma Splenectomy'] },
  { name: 'Liver Trauma Repair', specialtyName: 'Emergency', opcs4: ['J511'], commonVariations: ['Hepatic Laceration Repair'] },
  { name: 'Emergency Colostomy Formation', specialtyName: 'Emergency', opcs4: ['H104'], commonVariations: ['Hartmann Procedure'] },
  { name: 'Ischaemic Bowel Resection', specialtyName: 'Emergency', opcs4: ['G761', 'H061'], commonVariations: ['Mesenteric Ischaemia Surgery'] },
  { name: 'Volvulus Reduction and Fixation', specialtyName: 'Emergency', opcs4: ['H481'], commonVariations: ['Sigmoid Volvulus Surgery'] },
  { name: 'Gastric Volvulus Repair', specialtyName: 'Emergency', opcs4: ['G271'], commonVariations: ['Gastropexy'] },
  { name: 'Testicular Torsion Exploration', specialtyName: 'Emergency', opcs4: ['N181'], commonVariations: ['Scrotal Exploration', 'Orchidopexy'] },
  { name: 'Fournier Gangrene Debridement', specialtyName: 'Emergency', opcs4: ['S571'], commonVariations: ['Perineal Necrotising Fasciitis'] },
  { name: 'Emergency Tracheostomy', specialtyName: 'Emergency', opcs4: ['E421'], commonVariations: ['Urgent Airway'] },
  { name: 'Oesophageal Perforation Repair', specialtyName: 'Emergency', opcs4: ['G512'], commonVariations: ['Boerhaave Repair'] },
  { name: 'Pancreatic Trauma Repair', specialtyName: 'Emergency', opcs4: ['J511'], commonVariations: ['Pancreatic Injury Management'] },
  { name: 'Diaphragmatic Injury Repair', specialtyName: 'Emergency', opcs4: ['T271'], commonVariations: ['Diaphragm Repair'] },
  { name: 'Mesenteric Injury Repair', specialtyName: 'Emergency', opcs4: ['T511'], commonVariations: ['Mesenteric Haemorrhage Control'] },
  { name: 'Retroperitoneal Haematoma Exploration', specialtyName: 'Emergency', opcs4: ['T421'], commonVariations: ['Retroperitoneal Exploration'] },
  { name: 'Abdominal Wound Dehiscence Repair', specialtyName: 'Emergency', opcs4: ['T271'], commonVariations: ['Burst Abdomen Repair'] },
  { name: 'Emergency Relaparotomy', specialtyName: 'Emergency', opcs4: ['T421'], commonVariations: ['Second Look Laparotomy'] },

  // ============================================
  // ENDOSCOPY - ERCP (30 procedures)
  // ============================================
  { name: 'ERCP with Sphincterotomy', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['ERCP', 'Sphincterotomy'] },
  { name: 'ERCP with Stone Extraction', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J421'], commonVariations: ['CBD Stone Removal'] },
  { name: 'ERCP with Stent Insertion', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J441'], commonVariations: ['Biliary Stenting'] },
  { name: 'ERCP with Balloon Dilatation', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J501'], commonVariations: ['Stricture Dilatation'] },
  { name: 'ERCP with Brush Cytology', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J131'], commonVariations: ['Biliary Cytology'] },
  { name: 'ERCP with Biopsy', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J131'], commonVariations: ['Biliary Biopsy'] },
  { name: 'ERCP for Cholangitis', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['Therapeutic ERCP'] },
  { name: 'ERCP with Nasobiliary Drain', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J441'], commonVariations: ['NBD Insertion'] },
  { name: 'ERCP with Pancreatic Stent', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J441'], commonVariations: ['Pancreatic Duct Stenting'] },
  { name: 'ERCP for Ampullary Tumour', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J421'], commonVariations: ['Ampullary Resection'] },
  { name: 'ERCP with Metal Stent', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J441'], commonVariations: ['SEMS Insertion'] },
  { name: 'ERCP with Plastic Stent', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J441'], commonVariations: ['Biliary Plastic Stent'] },
  { name: 'ERCP Stent Removal', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J442'], commonVariations: ['Stent Extraction'] },
  { name: 'ERCP Stent Exchange', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J441'], commonVariations: ['Stent Replacement'] },
  { name: 'ERCP with Cholangioscopy', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J221'], commonVariations: ['SpyGlass', 'Direct Cholangioscopy'] },
  { name: 'ERCP with Lithotripsy', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J542'], commonVariations: ['Electrohydraulic Lithotripsy'] },
  { name: 'ERCP for Post-Operative Bile Leak', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J441'], commonVariations: ['Bile Leak Management'] },
  { name: 'ERCP for Biliary Stricture', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J501'], commonVariations: ['Stricture Therapy'] },
  { name: 'ERCP for Primary Sclerosing Cholangitis', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['PSC ERCP'] },
  { name: 'ERCP for Pancreatic Duct Disruption', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J441'], commonVariations: ['Pancreatic Leak Management'] },
  { name: 'ERCP for Chronic Pancreatitis', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['Therapeutic Pancreatography'] },
  { name: 'ERCP with Precut Sphincterotomy', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['Needle Knife Sphincterotomy'] },
  { name: 'ERCP with Biliary Balloon Sweep', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J421'], commonVariations: ['Stone Clearance'] },
  { name: 'ERCP with Mechanical Lithotripsy', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J542'], commonVariations: ['Basket Lithotripsy'] },
  { name: 'ERCP for Sphincter of Oddi Dysfunction', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['SOD Treatment'] },
  { name: 'ERCP with Manometry', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['Biliary Manometry'] },
  { name: 'ERCP for Recurrent Pyogenic Cholangitis', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['Oriental Cholangiohepatitis'] },
  { name: 'ERCP Post-Liver Transplant', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['Post-Transplant ERCP'] },
  { name: 'ERCP for Mirizzi Syndrome', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383'], commonVariations: ['Mirizzi ERCP'] },
  { name: 'ERCP with Papillary Balloon Dilation', specialtyName: 'Endoscopy', subspecialtyName: 'Endoscopic Retrograde Cholangiopancreatography', opcs4: ['J383', 'J501'], commonVariations: ['EPBD'] },

  // ============================================
  // ENDOSCOPY - Gastroscopy and Colonoscopy (30 procedures)
  // ============================================
  { name: 'Diagnostic Gastroscopy', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451'], commonVariations: ['OGD', 'Upper GI Endoscopy'] },
  { name: 'Diagnostic Colonoscopy', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['H201'], commonVariations: ['Colonoscopy'] },
  { name: 'Gastroscopy with Biopsy', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G131'], commonVariations: ['OGD + Biopsy'] },
  { name: 'Colonoscopy with Polypectomy', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['H201', 'H421'], commonVariations: ['Polyp Removal'] },
  { name: 'Colonoscopy with Biopsy', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['H201', 'H141'], commonVariations: ['Colon Biopsy'] },
  { name: 'Gastroscopy for Upper GI Bleeding', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G481'], commonVariations: ['Variceal Banding', 'Injection Therapy'] },
  { name: 'Colonoscopy for Lower GI Bleeding', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['H201', 'H491'], commonVariations: ['Therapeutic Colonoscopy'] },
  { name: 'Variceal Band Ligation', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G482'], commonVariations: ['EVL', 'Oesophageal Banding'] },
  { name: 'PEG Insertion - Endoscopic', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G413'], commonVariations: ['Percutaneous Endoscopic Gastrostomy'] },
  { name: 'Oesophageal Dilatation', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G501'], commonVariations: ['Stricture Dilatation', 'Bougie Dilatation'] },
  { name: 'Oesophageal Stent Insertion', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G451'], commonVariations: ['SEMS Oesophagus'] },
  { name: 'Gastric Ulcer Injection', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G481'], commonVariations: ['Adrenaline Injection'] },
  { name: 'Duodenal Ulcer Injection', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G481'], commonVariations: ['Endoscopic Haemostasis'] },
  { name: 'Endoscopic Mucosal Resection - Upper GI', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G421'], commonVariations: ['EMR Oesophagus'] },
  { name: 'Endoscopic Mucosal Resection - Colon', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['H201', 'H421'], commonVariations: ['EMR Colon'] },
  { name: 'Endoscopic Submucosal Dissection', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G421'], commonVariations: ['ESD'] },
  { name: 'Argon Plasma Coagulation - Upper GI', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G481'], commonVariations: ['APC Stomach'] },
  { name: 'Argon Plasma Coagulation - Colon', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['H201', 'H491'], commonVariations: ['APC Colon'] },
  { name: 'Gastric Polyp Removal', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G421'], commonVariations: ['Gastric Polypectomy'] },
  { name: 'Duodenal Polyp Removal', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G421'], commonVariations: ['Duodenal Polypectomy'] },
  { name: 'Flexible Sigmoidoscopy', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['H221'], commonVariations: ['Flexi Sig'] },
  { name: 'Foreign Body Removal - Upper GI', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G481'], commonVariations: ['FB Removal Oesophagus'] },
  { name: 'Colonic Stent Insertion', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['H201', 'H451'], commonVariations: ['Colonic SEMS'] },
  { name: 'Gastroscopy for Coeliac Disease', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G131'], commonVariations: ['Duodenal Biopsy'] },
  { name: 'Capsule Endoscopy Retrieval', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451'], commonVariations: ['Retained Capsule Removal'] },
  { name: 'Barrett Oesophagus Surveillance', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G131'], commonVariations: ['Barrett Surveillance'] },
  { name: 'Radiofrequency Ablation - Barrett', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G481'], commonVariations: ['RFA Barrett', 'Halo Ablation'] },
  { name: 'Endoscopic Clip Application', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G481'], commonVariations: ['Haemoclip Application'] },
  { name: 'Zenker Diverticulum Treatment', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G521'], commonVariations: ['Z-POEM'] },
  { name: 'Peroral Endoscopic Myotomy', specialtyName: 'Endoscopy', subspecialtyName: 'Gastroscopy and Colonoscopy', opcs4: ['G451', 'G521'], commonVariations: ['POEM'] },

  // ============================================
  // ENT - ENT Robotic (30 procedures)
  // ============================================
  { name: 'Robotic Transoral Laser Microsurgery', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['E271'], commonVariations: ['TORS', 'Robotic TLM'] },
  { name: 'Robotic Base of Tongue Resection', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['TORS BOT'] },
  { name: 'Robotic Tonsillectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F341'], commonVariations: ['Robotic Tonsils'] },
  { name: 'Robotic Supraglottic Laryngectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['E271'], commonVariations: ['TORS Supraglottis'] },
  { name: 'Robotic Vallecular Cyst Excision', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['Robotic Vallecula'] },
  { name: 'Robotic Lateral Oropharyngectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['TORS Lateral Pharyngeal Wall'] },
  { name: 'Robotic Glossectomy - Partial', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['Robotic Tongue Resection'] },
  { name: 'Robotic Hypopharyngeal Tumour Resection', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['TORS Hypopharynx'] },
  { name: 'Robotic Parapharyngeal Space Tumour', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['Robotic PPS Tumour'] },
  { name: 'Robotic Thyroidectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['B081'], commonVariations: ['Robotic Thyroid Surgery'] },
  { name: 'Robotic Parathyroidectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['B061'], commonVariations: ['Robotic Parathyroid'] },
  { name: 'Robotic Neck Dissection', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['E041'], commonVariations: ['Robotic Lymphadenectomy'] },
  { name: 'Robotic Laryngeal Papilloma Removal', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['E271'], commonVariations: ['TORS Papilloma'] },
  { name: 'Robotic Epiglottis Surgery', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['E271'], commonVariations: ['Robotic Epiglottectomy'] },
  { name: 'Robotic Pyriform Sinus Tumour Excision', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['TORS Pyriform Fossa'] },
  { name: 'Robotic Soft Palate Resection', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['TORS Soft Palate'] },
  { name: 'Robotic Uvulectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['Robotic Uvula Resection'] },
  { name: 'Robotic Arytenoidectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['E271'], commonVariations: ['Robotic Arytenoid Removal'] },
  { name: 'Robotic Vocal Cord Surgery', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['E271'], commonVariations: ['TORS Vocal Cords'] },
  { name: 'Robotic Lingual Tonsillectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F341'], commonVariations: ['Robotic Lingual Tonsils'] },
  { name: 'Robotic Pharyngeal Pouch Repair', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['Robotic Zenker Diverticulum'] },
  { name: 'Robotic Submandibular Gland Excision', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F211'], commonVariations: ['Robotic SMG Excision'] },
  { name: 'Robotic Parotidectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F201'], commonVariations: ['Robotic Parotid Surgery'] },
  { name: 'Robotic Retropharyngeal Lymph Node Biopsy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['E041'], commonVariations: ['TORS Node Biopsy'] },
  { name: 'Robotic Posterior Pharyngeal Wall Resection', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['TORS PPW'] },
  { name: 'Robotic Lingual Thyroid Removal', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['B081'], commonVariations: ['Robotic Ectopic Thyroid'] },
  { name: 'Robotic Sleep Apnoea Surgery', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['TORS OSA'] },
  { name: 'Robotic Palatoplasty', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['Robotic Palate Surgery'] },
  { name: 'Robotic Adenoidectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['E201'], commonVariations: ['Robotic Adenoids'] },
  { name: 'Robotic Pharyngoplasty', specialtyName: 'ENT', subspecialtyName: 'ENT Robotic', opcs4: ['F271'], commonVariations: ['Robotic Pharynx Reconstruction'] },

  // ============================================
  // ENT - ENT Laser (30 procedures)
  // ============================================
  { name: 'Laser Laryngeal Surgery', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['CO2 Laser Larynx'] },
  { name: 'Laser Vocal Cord Lesion Excision', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Vocal Cord Surgery'] },
  { name: 'Laser Laryngeal Papilloma Removal', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser RRP'] },
  { name: 'Laser Arytenoidectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Arytenoid Removal'] },
  { name: 'Laser Posterior Cordotomy', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Cordotomy'] },
  { name: 'Laser Supraglottoplasty', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Laryngomalacia Surgery'] },
  { name: 'Laser Subglottic Stenosis Treatment', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Airway Stenosis'] },
  { name: 'Laser Tonsillectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['F341'], commonVariations: ['Laser Tonsils'] },
  { name: 'Laser Adenoidectomy', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E201'], commonVariations: ['Laser Adenoids'] },
  { name: 'KTP Laser Vocal Cord Surgery', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['KTP Laser'] },
  { name: 'Laser Tongue Base Reduction', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['F271'], commonVariations: ['Laser BOT Reduction'] },
  { name: 'Laser Uvulopalatoplasty', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['F271'], commonVariations: ['LAUP'] },
  { name: 'Laser Pharyngoplasty', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['F271'], commonVariations: ['Laser Pharynx Surgery'] },
  { name: 'Laser Epiglottoplasty', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Epiglottis Surgery'] },
  { name: 'Laser Laryngeal Cyst Excision', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Laryngeal Cyst'] },
  { name: 'Laser Granuloma Removal - Larynx', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Vocal Granuloma'] },
  { name: 'Laser Reinke Oedema Treatment', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Polypoid Corditis'] },
  { name: 'Laser Laryngeal Web Division', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Web Lysis'] },
  { name: 'Laser Laryngeal Stenosis Treatment', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Stenosis Division'] },
  { name: 'Laser Nasal Turbinate Reduction', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E051'], commonVariations: ['Laser Turbinates'] },
  { name: 'Laser Inferior Turbinoplasty', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E051'], commonVariations: ['Laser IT'] },
  { name: 'Laser Treatment of Hereditary Haemorrhagic Telangiectasia', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E051'], commonVariations: ['Laser HHT'] },
  { name: 'Laser Stapedotomy', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['D161'], commonVariations: ['Laser Stapes Surgery'] },
  { name: 'Laser Myringotomy', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['D151'], commonVariations: ['Laser Ear Drum'] },
  { name: 'Laser Pharyngeal Tumour Ablation', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['F271'], commonVariations: ['Laser Pharynx Tumour'] },
  { name: 'Laser Laryngeal Tumour Excision', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Larynx Cancer'] },
  { name: 'Laser Glottic Tumour Resection', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Glottis'] },
  { name: 'Laser Leukoplakia Excision - Larynx', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser Leukoplakia'] },
  { name: 'Laser Posterior Glottic Stenosis Repair', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser PGS'] },
  { name: 'Laser Bilateral Vocal Cord Paralysis Surgery', specialtyName: 'ENT', subspecialtyName: 'ENT Laser', opcs4: ['E271'], commonVariations: ['Laser BVCP'] },

];

console.log(JSON.stringify(procedures, null, 2));
console.log(`\nTotal procedures so far: ${procedures.length}`);
